language: node_js
sudo: required
dist: trusty
services:
  - docker
node_js:
  - "6"
before_install:
  - docker pull node:latest
before_script:
  - npm install -g bunyan
script:
  - npm run test
after_success:
  - npm run coveralls
